name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm i -g @redocly/cli@1.6.0

    - name: Lint spec
      run: redocly lint ./beacon-node-oapi.yaml

    - name: Bundle spec
      run: "redocly bundle ./beacon-node-oapi.yaml --remove-unused-components  -d --ext yaml -o ./deploy/beacon-node-oapi.yaml"
